name: e_book
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter packages
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  carousel_slider: ^5.1.1
  go_router: ^12.1.3

  # Firebase packages
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_database: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/onboarding_books.jpg
    - assets/images/splash.png

  